[supervisord]
nodaemon=true

[program:clickhouse]
command=/usr/bin/clickhouse-server
autostart=true
autorestart=true

[program:backend]
directory=/app/backend
command=/app/backend/signoz-server
autostart=true
autorestart=true

[program:frontend]
directory=/app/frontend
command=yarn dev
autostart=true
autorestart=true
